services:
  - type: web
    name: portfolio-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: static
    name: portfolio-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
